CREATE DATABASE IF NOT EXISTS cas;

USE cas;

CREATE USER 'cas'@'localhost' IDENTIFIED BY '1';
CREATE USER 'cas_admin'@'localhost' IDENTIFIED BY '2'; 
 
CREATE TABLE IF NOT EXISTS `USERS`
(
 `ID`         INT(11) NOT NULL AUTO_INCREMENT COMMENT 'User unique ID',
 `NAME`       VARCHAR(50) NOT NULL COMMENT 'User name (login)',
 `PASS`       VARCHAR(35) NULL DEFAULT NULL COMMENT 'User password hash',
 `POINTS`     INT(11) NOT NULL DEFAULT 0 COMMENT 'User balance',
 `SESSION_ID` VARCHAR(35) NULL DEFAULT NULL COMMENT 'Session identifier',
 `ACTIVITY`   DATETIME NULL DEFAULT NULL COMMENT 'Last user activity date and time',
 `ADDR`       VARCHAR(46) NULL DEFAULT NULL COMMENT 'User IP address',
 `STATUS_ID`  INT(1) NULL DEFAULT NULL COMMENT 'Last status of the play',

 PRIMARY KEY (`ID`),
 UNIQUE INDEX `IDX_USERS`(`NAME`)
)
COMMENT='Users table'
AUTO_INCREMENT=1 
DEFAULT CHARSET=utf8
Engine=InnoDB;

CREATE INDEX `IDX_USERS1` ON `USERS` (`STATUS_ID`);
CREATE INDEX `IDX_USERS2` ON `USERS` (`SESSION_ID`);

CREATE TABLE IF NOT EXISTS `PRIZES` (
 `ID`         INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Prize unique ID',
 `TYPE`	      INT(1) NOT NULL DEFAULT 1 COMMENT 'Prize type',
 `NAME`       VARCHAR(30) NOT NULL COMMENT 'Prize name',
 `COUNT`      INT(6) NOT NULL DEFAULT 0 COMMENT 'Prize rest count',
 `POINTS`     INT(3) NOT NULL DEFAULT 0 COMMENT 'Convert rate to points',    	 

 PRIMARY KEY (`ID`),
 UNIQUE INDEX `IDX_PRIZES`(`NAME`) 
)
COMMENT='Prizes table'
AUTO_INCREMENT=1 
DEFAULT CHARSET=utf8
Engine=InnoDB;

CREATE INDEX `IDX_PRIZES1` ON `PRIZES` (`TYPE`);

CREATE TABLE IF NOT EXISTS `STATUSES` (
 `ID`         INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Status unique ID',
 `USER_ID`    INT(1) NOT NULL COMMENT 'User ID',
 `PRIZE_ID`   INT(11) NOT NULL COMMENT 'Prize type',
 `COUNT`      INT(11) NOT NULL DEFAULT 0 COMMENT 'Count of the prizes', 
 `STATUS`     INT(1) NOT NULL DEFAULT 1 COMMENT 'Prize status: 1 - new, 2 - send, 3 - complete, 4 - cancel',

 PRIMARY KEY (`ID`),
 FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`)
   ON DELETE CASCADE,
 FOREIGN KEY (`PRIZE_ID`) REFERENCES `PRIZES`(`ID`)
   ON DELETE CASCADE
)
COMMENT='Statuses table'
AUTO_INCREMENT=1 
DEFAULT CHARSET=utf8
Engine=InnoDB;

CREATE INDEX `IDX_STATUSES` ON `STATUSES` (`USER_ID`);
CREATE INDEX `IDX_STATUSES1` ON `STATUSES` (`PRIZE_ID`);


GRANT UPDATE,SELECT ON `USERS` TO 'cas'@'localhost';
GRANT UPDATE,SELECT ON `PRIZES` TO 'cas'@'localhost';
GRANT INSERT,UPDATE,SELECT ON `STATUSES` TO 'cas'@'localhost';
GRANT INSERT,UPDATE,DELETE,SELECT ON `USERS` TO 'cas_admin'@'localhost';
GRANT INSERT,UPDATE,DELETE,SELECT ON `PRIZES` TO 'cas_admin'@'localhost';
GRANT INSERT,UPDATE,DELETE,SELECT ON `STATUSES` TO 'cas'@'localhost';
FLUSH PRIVILEGES;